trade:
  expiry:
    schedule: "0/30 * * * *"
spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: sa
    password:

spring.h2.console.enabled: true
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect